name: Smoke test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions: {}
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container:
      image: gwennlbh/playwright-bun:v1.62.1@sha256:ed174f1e7cad210ef3d1069b86c5ceedf5bb026b57d8edbb9aa4c3ba7394fff0
      options: --user 1001
    steps:
      - name: Git Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Bun setup
        uses: ./.github/actions/setup

      - name: Smoke & Acceptance tests
        run: bunx vitest run --project storybook
        env:
          FORCE_COLOR: "1"
